### ISSUE TITLE
Additinal Fields Integration (e.g. KeeOTP)

### ISSUE THREAD

**Issue by sirrus** [smorks/keepasshttp-connector#26]
Could you please implement additional Fields?
For example the Autotype for KeeOTP  = {TOTP}?

Regards
Andreas

**Comment by smorks** [comment]
i believe you should be able to do it, see here: 

https://github.com/smorks/keepasshttp-connector/blob/master/documentation/KeePassHttp-Connector.md#37-fill-in-additional-values-via-string-fields

i haven't tested it, but if you have issues, let me know.

**Comment by Arjoni** [comment]
@smorks I can not understand how to do that. Can you please make a video to explain this?

**Comment by andschwa** [comment]
@smorks Do you know if this possible to do with KeePassXC? I don't see an equivalent option in their version of KeePassHttp. I'd love to fill in a TOTP field as "String field #1".

**Comment by andschwa** [comment]
@Arjoni Are you using KeePass or KeePassXC?

@smorks For what it's worth, this _is_ possible with KeePassXC, it's just not well documented. It also requires building the development version because https://github.com/keepassxreboot/keepassxc/pull/1072 wasn't included in the latest release. (And I mean `develop` branch; I tried just cherry-picking it, but it wasn't enough.)

In short: go to the entry in KeePassXC, click "Advanced", add a new field named `KPH: String field #1` (etc., the `KPH: ` prefix is required, and the option under "Browser Integration" settings must be enabled), and enter `{TOTP}` for the content. Then it will autofill following the same rules as their [Autotype Custom Sequence](https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence).
