### ISSUE TITLE
Password not being saved into KeePass

### ISSUE THREAD

**Issue by BWMerlin** [smorks/keepasshttp-connector#45]
When ever I get prompted to save a password by Firefox it is then not passing this onto KeePass.  Happens on all pages.  When I was using Pass|Fox any time I clicked save those passwords were saved into my KeePass database.  I have tried disconnecting and reconnecting Http-Connector and still get this issue.

    The extension are you using and its version
KeePassHttp-Connector Version: 1.0.8
    Version of your browser
Firefox x64 57.0
    KeePassHttp version
1.8.4.2
    KeePass/KeePassXC version
KeePass: 2.37
    Pages on which the error occur
Every page that prompts you to save a password.

**Comment by smorks** [comment]
with the new WebExtension API that firefox uses, there is no way to tie into the built-in password manager. you can either ignore those prompts or disable it in the firefox options.

in order to save new credentials, when you submit the form, the KeePassHttp-Connector icon should flash red. when you click on it, it will give you a chance to save them to KeePass.
