### ISSUE TITLE
Re-brand and Publish on AMO/Chrome Web Store?

### ISSUE THREAD

**Issue by Ivan0xFF** [smorks/keepasshttp-connector#8]
The original chromeipass/passifox seem to be abandoned. Maybe it's time to re-brand and publish this updated version? Otherwise we might be left with no compatible Keepass extension for Firefox available on AMO when 57 rolls around.

**Comment by smorks** [comment]
i've been thinking about this too. it would be nice to have a generic name for both chrome & firefox, and then once it's in AMO/Chrome Web Store, it would be auto-updating in both browsers then too.

i'm open to name suggestions, as i have no good ideas currently, haha.

**Comment by varjolintu** [comment]
How about just keepass-browser? It's a neutral name but a good description. And it doesn't include any other browser names.

**Comment by Ivan0xFF** [comment]
I like it, but won't it get confusing with your keepassxc-browser?

**Comment by varjolintu** [comment]
@Ivan0xFF Maybe. That's why your suggestions are good. Not too near of my extension.

**Comment by smorks** [comment]
i was initially thinking BrowserIPass too, but also like having the KeePassHTTP in the name as well, since it's a requirement.

for one more variation: KeePassHTTP-Connector?

**Comment by Ivan0xFF** [comment]
I think my favorites are:
KeePassHTTP-Connector
KeePassHTTP-Browser
BrowserIPass

In that order.

**Comment by sameyepatch** [comment]
Hello,

I don't know if you agree with me but a new icon might come handy as well. The reason I'm telling you this is that when I saw this new extension in the Chrome Store I was confused since I've been using chromeipass for a while, and thought this new extension was just a clone (and I'm used to see and report malicious clones of extensions).

Or, if not a new icon, at least a better description on how this extension is a better than the older one (abandoned project, deprecation, etc). If not a better description in the store, something in the Github project that specifies the reason for a fork. Because, sincerely, it threw me off for a moment.

Thanks.

**Comment by smorks** [comment]
@sameyepatch i have thought about changing the icon. i believe the icon that it uses is just the KeePass icon, so that could be improved.

in the meantime i'll update the description in the web store and in the readme that better explains the need for the fork.

thanks for your input!

**Comment by erikvanoosten** [comment]
The names that end on `-browser` are really confusing. This is a plugin, not a browser!

My humble +1 goes to KeePass-Connector, mostly because it makes crystal clear what is does.
